// import { AlbertSans } from "next/font/google"
import Header from "@/components/layout/header";
import "../styles/global.scss";
import { ReduxProvider } from "@/lib/redux/provider";

// export const albertsans = AlbertSans({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-primary",
// })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Header />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
